import type { Listing, BookingInfo, Vendor } from "@/types";

export const VENDORS: Vendor[] = [
  {
    id: "v1",
    name: "Adekay Houses",
    verified: true,
    yearsOnPlatform: 3,
    dateRegistered: "June 26, 2024",
    availability: "typically_available",
  },
  {
    id: "v2",
    name: "Auto Giell",
    verified: true,
    yearsOnPlatform: 3,
    dateRegistered: "June 26, 2024",
    availability: "typically_available",
  },
  {
    id: "v3",
    name: "Minkail Autos",
    verified: true,
    yearsOnPlatform: 2,
    dateRegistered: "March 12, 2024",
    availability: "typically_available",
  },
  {
    id: "v4",
    name: "Darry Autos",
    verified: true,
    yearsOnPlatform: 1,
    dateRegistered: "January 5, 2025",
    availability: "typically_available",
  },
  {
    id: "v5",
    name: "Sure Lets",
    verified: true,
    yearsOnPlatform: 2,
    dateRegistered: "August 10, 2023",
    availability: "typically_available",
  },
  {
    id: "v6",
    name: "Darry Lets",
    verified: false,
    yearsOnPlatform: 1,
    dateRegistered: "February 2, 2024",
    availability: "typically_available",
  },
  {
    id: "v7",
    name: "Merith House",
    verified: true,
    yearsOnPlatform: 4,
    dateRegistered: "April 15, 2022",
    availability: "typically_available",
  },
  {
    id: "v8",
    name: "Carbuddy",
    verified: true,
    yearsOnPlatform: 2,
    dateRegistered: "May 20, 2023",
    availability: "typically_available",
  },
  {
    id: "v9",
    name: "Greyman Security Service",
    verified: true,
    yearsOnPlatform: 3,
    dateRegistered: "June 25, 2024",
    availability: "typically_available",
  },
];

export const SAFETY_TIPS = [
  "Do not make any inspection fee without seeing the agent and property.",
  "Only pay Rental fee, Sales fee or any upfront payment after you verify the Landlord.",
  "Ensure you meet the Agent in an open location.",
  "The Agent does not represent LunarFortis and LunarFortis is not liable for any monetary transaction between you and the Agent.",
];

export const APARTMENT_IMAGES = [
  "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80",
  "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80",
  "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=600&q=80",
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80",
  "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80",
];

export const CAR_IMAGES = [
  "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=600&q=80",
  "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=600&q=80",
  "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=600&q=80",
  "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=600&q=80",
];

export const SECURITY_IMAGES = [
  "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=600&q=80",
  "https://images.unsplash.com/photo-1579829366248-204fe8413f31?w=600&q=80",
  "https://images.unsplash.com/photo-1583195764036-46e3b2c6b4e1?w=600&q=80",
  "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
];

export const HERO_IMAGE =
  "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&q=80";

export const LISTINGS: Listing[] = [
  // Apartments
  {
    id: "apt-1",
    type: "accommodation",
    title: "3 Bedroom Apartment",
    images: [APARTMENT_IMAGES[0], APARTMENT_IMAGES[1], APARTMENT_IMAGES[2]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[0],
    tags: ["6 Guests", "Wifi", "Automatic"],
    amenities: ["Wifi", "Automatic", "24hr Light"],
    guests: 6,
    description:
      "Fully Furnished Single Room Shortlet for Rent ?? Location: Agungi, Lekki, Lagos Easily accessible via Osapa London ?? Rate: ? 40,000 per day ? Open to Long Stay Features: • Private Kitchen • Toilet & Bathroom • Water Heater • Microwave • 24/7 Water Supply • 24/7 Electricity • Air Conditioner • Netflix • Gym • Football Pitch Available for shortlet and long stay.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "apt-2",
    type: "accommodation",
    title: "Studio Apartment",
    images: [APARTMENT_IMAGES[1], APARTMENT_IMAGES[4], APARTMENT_IMAGES[5]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[5],
    tags: ["4 Guests", "Wifi", "24hr Light"],
    amenities: ["Wifi", "24hr Light"],
    guests: 4,
    description:
      "Cozy studio apartment in the heart of Lekki. Perfect for short-term stays with all modern amenities.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "apt-3",
    type: "accommodation",
    title: "3 Bedroom Apartment",
    images: [APARTMENT_IMAGES[2], APARTMENT_IMAGES[6], APARTMENT_IMAGES[7]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[4],
    tags: ["4 Guests", "Wifi", "24hr Light"],
    amenities: ["Wifi", "24hr Light"],
    guests: 4,
    description:
      "Spacious 3 bedroom apartment with premium furnishings in Lekki. Great for families or groups.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "apt-4",
    type: "accommodation",
    title: "2 Bedroom Apartment",
    images: [APARTMENT_IMAGES[3], APARTMENT_IMAGES[0], APARTMENT_IMAGES[1]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[6],
    tags: ["2 Guests", "Wifi", "24hr Light"],
    amenities: ["Wifi", "24hr Light", "Air Condition"],
    guests: 2,
    description:
      "Fully Furnished Single Room Shortlet for Rent ?? Location: Agungi, Lekki, Lagos Easily accessible via Osapa London ?? Rate: ? 40,000 per day ? Open to Long Stay Features: • Private Kitchen • Toilet & Bathroom • Water Heater • Microwave • 24/7 Water Supply • 24/7 Electricity • Air Conditioner • Netflix • Gym • Football Pitch Available for shortlet and long stay.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "apt-5",
    type: "accommodation",
    title: "3 Bedroom Apartment",
    images: [APARTMENT_IMAGES[4], APARTMENT_IMAGES[2], APARTMENT_IMAGES[3]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[0],
    tags: ["6 Guests", "Wifi", "Automatic"],
    amenities: ["Wifi", "Automatic"],
    guests: 6,
    description: "Luxury 3 bedroom apartment in Lekki with pool access.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "apt-6",
    type: "accommodation",
    title: "3 Bedroom Apartment",
    images: [APARTMENT_IMAGES[5], APARTMENT_IMAGES[1], APARTMENT_IMAGES[6]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[4],
    tags: ["4 Guests", "Wifi", "Automatic"],
    amenities: ["Wifi", "Automatic"],
    guests: 4,
    description: "Modern 3 bedroom apartment near Lekki Phase 1.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "apt-7",
    type: "accommodation",
    title: "2 Bedroom Apartment",
    images: [APARTMENT_IMAGES[6], APARTMENT_IMAGES[3], APARTMENT_IMAGES[0]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[6],
    tags: ["2 Guests", "Wifi", "24hr Light"],
    amenities: ["Wifi", "24hr Light"],
    guests: 2,
    description: "Comfortable 2 bedroom apartment with all amenities.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "apt-8",
    type: "accommodation",
    title: "Studio Apartment",
    images: [APARTMENT_IMAGES[7], APARTMENT_IMAGES[4], APARTMENT_IMAGES[5]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[5],
    tags: ["4 Guests", "Wifi", "24hr Light"],
    amenities: ["Wifi", "24hr Light"],
    guests: 4,
    description: "Modern studio apartment with stunning city views.",
    safetyTips: SAFETY_TIPS,
  },

  // Cars
  {
    id: "car-1",
    type: "car",
    title: "Land Cruiser Prado 2025",
    images: [CAR_IMAGES[0], CAR_IMAGES[1], CAR_IMAGES[2]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[2],
    tags: ["Black", "Petrol", "Automatic"],
    color: "Black",
    fuel: "Petrol",
    transmission: "Automatic",
    description:
      "Fully Furnished Single Room Shortlet for Rent ?? Location: Agungi, Lekki, Lagos Easily accessible via Osapa London ?? Rate: ? 40,000 per day ? Open to Long Stay Features: • Private Kitchen • Toilet & Bathroom • Water Heater • Microwave • 24/7 Water Supply • 24/7 Electricity • Air Conditioner • Netflix • Gym • Football Pitch Available for shortlet and long stay.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "car-2",
    type: "car",
    title: "Land Cruiser Prado 2025",
    images: [CAR_IMAGES[1], CAR_IMAGES[2], CAR_IMAGES[3]],
    pricePerDay: 97000,
    location: "Ikeja",
    vendor: VENDORS[1],
    tags: ["Black", "Petrol", "Manual"],
    color: "Black",
    fuel: "Petrol",
    transmission: "Manual",
    description: "Premium Land Cruiser Prado available for hire in Ikeja.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "car-3",
    type: "car",
    title: "Land Cruiser Prado 2025",
    images: [CAR_IMAGES[2], CAR_IMAGES[0], CAR_IMAGES[1]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[7],
    tags: ["Black", "Gasoline", "Automatic"],
    color: "Black",
    fuel: "Gasoline",
    transmission: "Automatic",
    description: "Top-of-the-line Land Cruiser Prado in Lekki.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "car-4",
    type: "car",
    title: "Land Cruiser Prado 2025",
    images: [CAR_IMAGES[3], CAR_IMAGES[1], CAR_IMAGES[2]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[3],
    tags: ["Black", "Petrol", "Automatic"],
    color: "Black",
    fuel: "Petrol",
    transmission: "Automatic",
    description: "Luxury Land Cruiser Prado available for chauffeur-driven hire.",
    safetyTips: SAFETY_TIPS,
  },

  // Security
  {
    id: "sec-1",
    type: "security",
    title: "Greyman Security Service",
    images: [SECURITY_IMAGES[0], SECURITY_IMAGES[1], SECURITY_IMAGES[2]],
    pricePerDay: 97000,
    location: "Ikeja",
    vendor: VENDORS[8],
    tags: ["Armed Escort", "Security", "Hilux"],
    serviceType: "Armed Escort • Security • Hilux",
    description:
      "Fully Furnished Single Room Shortlet for Rent ?? Location: Agungi, Lekki, Lagos Easily accessible via Osapa London ?? Rate: ? 40,000 per day ? Open to Long Stay Features: • Private Kitchen • Toilet & Bathroom • Water Heater • Microwave • 24/7 Water Supply • 24/7 Electricity • Air Conditioner • Netflix • Gym • Football Pitch Available for shortlet and long stay.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "sec-2",
    type: "security",
    title: "Land Cruiser Prado 2025",
    images: [SECURITY_IMAGES[1], SECURITY_IMAGES[2], SECURITY_IMAGES[3]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[7],
    tags: ["Armed Escort", "Security", "Hilux"],
    serviceType: "Armed Escort • Security • Hilux",
    description: "Armed security escort with Land Cruiser Prado.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "sec-3",
    type: "security",
    title: "Land Cruiser Prado 2025",
    images: [SECURITY_IMAGES[2], SECURITY_IMAGES[0], SECURITY_IMAGES[1]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[2],
    tags: ["Armed Escort", "Security", "Hilux"],
    serviceType: "Armed Escort • Security • Hilux",
    description: "Professional armed security with premium vehicle.",
    safetyTips: SAFETY_TIPS,
  },
  {
    id: "sec-4",
    type: "security",
    title: "Land Cruiser Prado 2025",
    images: [SECURITY_IMAGES[3], SECURITY_IMAGES[1], SECURITY_IMAGES[2]],
    pricePerDay: 97000,
    location: "Lekki",
    vendor: VENDORS[3],
    tags: ["Armed Escort", "Security", "Hilux"],
    serviceType: "Armed Escort • Security • Hilux",
    description: "Top-tier security escort service in Lagos.",
    safetyTips: SAFETY_TIPS,
  },
];

export const MOCK_BOOKING: BookingInfo = {
  id: "b1",
  orderId: "#BKG123456-2N",
  status: "accepted",
  createdDate: "09 April 2026, 10:45 AM",
  listing: LISTINGS.find((l) => l.id === "car-1")!,
  location: "Lekki Peninsula",
  startDate: "09 April 2026",
  endDate: "10 April 2026",
  pickupTime: "12:00 PM",
  preference: "Chauffeur-driven",
  geography: "Interstate",
  numberOfDays: 2,
  totalBilling: 102000,
  countdown: 7169,
  trackingProgress: [
    {
      key: "initiated",
      label: "Booking Initiated",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "received",
      label: "Booking Received by Vendor",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "accepted",
      label: "Booking Accepted",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "payment",
      label: "Payment Successful",
      time: "Jan 19, 9:15 AM",
      completed: false,
    },
    {
      key: "success",
      label: "Booking Successful",
      time: "Jan 19, 9:11 AM",
      completed: false,
    },
  ],
};

export const MOCK_BOOKING_APARTMENT: BookingInfo = {
  id: "b2",
  orderId: "#BKG123456-2N",
  status: "accepted",
  createdDate: "09 April 2026, 10:45 AM",
  listing: LISTINGS.find((l) => l.id === "apt-4")!,
  location: "Lekki Peninsula",
  startDate: "09 April 2026",
  endDate: "10 April 2026",
  checkInDate: "09 April 2026",
  checkOutDate: "10 April 2026",
  checkInTime: "12:00 PM",
  numberOfDays: 2,
  totalBilling: 194000,
  countdown: 7198,
  trackingProgress: [
    {
      key: "initiated",
      label: "Booking Initiated",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "received",
      label: "Booking Received by Vendor",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "accepted",
      label: "Booking Accepted",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "payment",
      label: "Payment Successful",
      time: "Jan 19, 9:15 AM",
      completed: false,
    },
    {
      key: "success",
      label: "Booking Successful",
      time: "Jan 19, 9:11 AM",
      completed: false,
    },
  ],
};

export const COMPLETED_BOOKING: BookingInfo = {
  ...MOCK_BOOKING_APARTMENT,
  id: "b3",
  status: "completed",
  trackingProgress: [
    {
      key: "initiated",
      label: "Booking Initiated",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "received",
      label: "Booking Received by Vendor",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "accepted",
      label: "Booking Accepted",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
    {
      key: "payment",
      label: "Payment Successful",
      time: "Jan 19, 9:15 AM",
      completed: true,
    },
    {
      key: "success",
      label: "Booking Successful",
      time: "Jan 19, 9:11 AM",
      completed: true,
    },
  ],
};

export function formatPrice(amount: number): string {
  return `₦${amount?.toLocaleString("en-NG")}`;
}
